### ISSUE TITLE
# Prepare payment from xrpl.models.transactions import Payment from xrpl.utils import xrp_to_drops my_tx_payment = Payment(     account=test_account,     amount=xrp_to_drops(22),     destination="rPT1Sjq2YGrBMTttX4GZHjKu9dyfzbpAYe", )

### ISSUE THREAD

**Issue by antliv** [xpring-eng/testnet-faucet#9]
Fuckin skumbad i reported u

**Comment by antliv** [comment]
Can someone help me w this

**Comment by natenichols** [comment]
Hi @antliv, thanks for opening an issue. 

Do you have a code snippet that consistently reproduces this issue, or any information about how you are calling the testnet faucet?

**Comment by antliv** [comment]
Im not sure i got like3k messages sayin the same thing
